# Generated by Django 5.2.11 on 2026-04-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_attendeeplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutinformation',
            name='bank_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payoutinformation',
            name='recipient_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
