# Generated by Django 5.2.11 on 2026-04-13 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_payoutinformation_bank_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payoutinformation',
            constraint=models.UniqueConstraint(fields=('user', 'bank_name', 'account_number'), name='unique_user_payout_account'),
        ),
    ]
