# Generated by Django 5.2.11 on 2026-04-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payoutinformation_unique_user_payout_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
    ]
