# Generated by Django 5.2.11 on 2026-02-16 23:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('host', '0001_initial'),
        ('public', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('single', 'Single Event'), ('recurring', 'Recurring Event')], max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location_type', models.CharField(choices=[('physical', 'Physical Venue'), ('online', 'Online Event'), ('tba', 'To Be Announced')], max_length=20)),
                ('short_description', models.CharField(max_length=160)),
                ('full_description', models.TextField(max_length=5000)),
                ('organizer_display_name', models.CharField(max_length=255)),
                ('organizer_description', models.TextField(blank=True, max_length=500)),
                ('public_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('refund_policy', models.CharField(choices=[('no', 'No Refund'), ('partial', 'Partial'), ('full', 'Full'), ('custom', 'Custom')], max_length=20)),
                ('refund_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('qr_enabled', models.BooleanField(default=True)),
                ('age_restriction', models.BooleanField(default=False)),
                ('order_confirmation', models.BooleanField(default=True)),
                ('ticket_delivery', models.BooleanField(default=True)),
                ('reminders', models.BooleanField(default=False)),
                ('post_event_emails', models.BooleanField(default=False)),
                ('customize_sender_name', models.BooleanField(default=False)),
                ('affiliate_enabled', models.BooleanField(default=False)),
                ('commission_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('affiliate_start', models.DateTimeField(blank=True, null=True)),
                ('affiliate_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.category')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoster', to='host.host')),
                ('tags', models.ManyToManyField(blank=True, to='events.tag')),
            ],
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('host', 'Host'), ('collaborator', 'Collaborator'), ('financial', 'Financial')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('pending', 'Pending Invitation')], max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('per_person_max', models.PositiveIntegerField()),
                ('sales_start', models.DateTimeField()),
                ('sales_end', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discount_percentage', models.PositiveIntegerField()),
                ('maximum_users', models.PositiveIntegerField()),
                ('valid_till', models.DateField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='events.ticket')),
            ],
        ),
    ]
