# Generated by Django 5.2.11 on 2026-02-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('sold-out', 'Sold-Out'), ('banned', 'Banned')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventpermission',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('disabled', 'Disabled'), ('pending', 'Pending Invitation')], default='pending', max_length=20),
        ),
    ]
