# Generated by Django 5.2.11 on 2026-02-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_status_alter_eventpermission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpermission',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('pending', 'Pending Invitation')], default='pending', max_length=20),
        ),
    ]
