# Generated by Django 5.2.11 on 2026-02-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventpermission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpermission',
            name='user',
        ),
        migrations.AddField(
            model_name='eventpermission',
            name='email',
            field=models.EmailField(default='ebubeidika@gmail.com', max_length=254),
        ),
    ]
