# Generated by Django 5.2.11 on 2026-02-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_eventpermission_user_eventpermission_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpermission',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
