# Generated by Django 5.2.11 on 2026-02-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_saves_count_event_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('sold-out', 'Sold-Out'), ('ended', 'Ended'), ('cancelled', 'Cancelled'), ('banned', 'Banned')], default='active', max_length=20),
        ),
    ]
