# Generated by Django 5.2.11 on 2026-02-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sold_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
