# Generated by Django 5.2.11 on 2026-03-16 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_ticket_sold_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlocation',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_location', to='events.event'),
        ),
    ]
