# Generated by Django 5.2.11 on 2026-03-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_eventlocation_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
    ]
