# Generated by Django 5.2.11 on 2026-04-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
