# Generated by Django 5.2.11 on 2026-04-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_commission_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='schedule_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
