# Generated by Django 5.2.11 on 2026-04-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_is_scheduled_event_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlocation',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='venue_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
