# Generated by Django 5.2.11 on 2026-04-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_eventlocation_address_alter_eventlocation_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='minimum_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
