# Generated by Django 5.2.11 on 2026-04-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_minimum_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('sold-out', 'Sold-Out'), ('ended', 'Ended'), ('cancelled', 'Cancelled'), ('banned', 'Banned'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
    ]
