# Generated by Django 5.2.11 on 2026-02-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0002_attendee_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffliateEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning', models.PositiveIntegerField()),
            ],
        ),
    ]
