# Generated by Django 5.2.11 on 2026-02-23 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0003_affliateearnings'),
        ('host', '0005_affliate'),
    ]

    operations = [
        migrations.AddField(
            model_name='affliateearnings',
            name='affliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='host.affliate'),
        ),
        migrations.AddField(
            model_name='affliateearnings',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='attendee.attendee'),
        ),
    ]
