# Generated by Django 5.2.11 on 2026-02-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0004_affliateearnings_affliate_affliateearnings_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='affliateearnings',
            name='create_at',
            field=models.DateField(auto_now=True),
        ),
    ]
