# Generated by Django 5.2.11 on 2026-02-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0005_affliateearnings_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affliateearnings',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
