# Generated by Django 5.2.11 on 2026-02-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0008_remove_affliateearnings_affliate_affiliatelink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affliateearnings',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending'),
        ),
    ]
