# Generated by Django 5.2.11 on 2026-02-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0010_payoutinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendee',
            name='gender',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attendee',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
