# Generated by Django 5.2.11 on 2026-03-05 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0014_attendee_show_events_attending_and_more'),
        ('transactions', '0010_alter_withdrawal_payout_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payoutinformation',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivitySharingSettings',
        ),
        migrations.DeleteModel(
            name='PayoutInformation',
        ),
    ]
