# Generated by Django 5.2.11 on 2026-03-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0015_remove_payoutinformation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affliateearnings',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('hold', 'Hold')], default='pending'),
        ),
    ]
