# Generated by Django 5.2.11 on 2026-03-18 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0016_alter_affliateearnings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affliateearnings',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='attendee.affiliatelink'),
        ),
    ]
