# Generated by Django 5.2.11 on 2026-03-18 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0017_alter_affliateearnings_link'),
        ('transactions', '0013_issuedticket_guest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affliateearnings',
            name='earning_type',
            field=models.CharField(choices=[('affiliate', 'Affiliate Commission'), ('marketplace', 'Marketplace Sale')], default='affiliate', max_length=20),
        ),
        migrations.AddField(
            model_name='affliateearnings',
            name='marketplace_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_earnings', to='transactions.order'),
        ),
    ]
