# Generated by Django 5.2.11 on 2026-03-18 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0018_affliateearnings_earning_type_and_more'),
        ('transactions', '0013_issuedticket_guest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affliateearnings',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_earnings', to='transactions.order'),
        ),
    ]
