# Generated by Django 5.2.11 on 2026-03-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0019_affliateearnings_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affliateearnings',
            name='order',
        ),
    ]
