# Generated by Django 5.2.11 on 2026-03-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0020_remove_affliateearnings_order'),
        ('public', '0008_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='attendees', to='public.category'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
