# Generated by Django 5.2.11 on 2026-04-01 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0021_alter_attendee_categories_alter_attendee_city_and_more'),
        ('payments', '0008_attendeeplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('free', 'Free')], default='free', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('plan_slug', models.CharField(default='free', max_length=20)),
                ('currency', models.CharField(default='NGN', help_text='Currency used for this subscription (NGN, USD, GHS, KES, ZAR, etc.)', max_length=3)),
                ('metadata', models.JSONField(default=dict)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='attendee.attendee')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.attendeeplan')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
