# Generated by Django 5.2.11 on 2026-04-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0022_attendeesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatelink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
