# Generated by Django 5.2.11 on 2026-02-24 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_order_confirmations', models.BooleanField(default=True)),
                ('email_ticket_delivery', models.BooleanField(default=True)),
                ('email_event_reminders', models.BooleanField(default=False)),
                ('email_price_drop_alerts', models.BooleanField(default=False)),
                ('email_similar_events', models.BooleanField(default=False)),
                ('email_weekly_digest', models.BooleanField(default=False)),
                ('email_promotional_offers', models.BooleanField(default=False)),
                ('email_account_security', models.BooleanField(default=True)),
                ('sms_order_confirmations', models.BooleanField(default=False)),
                ('sms_event_reminders', models.BooleanField(default=False)),
                ('sms_promotional_offers', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
