# Generated by Django 5.2.11 on 2026-02-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketTransferHistory',
        ),
    ]
