# Generated by Django 5.2.11 on 2026-02-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_issuedticket_splitpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SplitPayment',
        ),
    ]
