# Generated by Django 5.2.11 on 2026-02-24 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_delete_tickettransferhistory'),
        ('transactions', '0006_tickettransferhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='marketplace_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.marketlisting'),
        ),
    ]
