# Generated by Django 5.2.11 on 2026-02-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='idempotency_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
