# Generated by Django 5.2.11 on 2026-03-05 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payoutinformation'),
        ('transactions', '0009_withdrawal_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='payout_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.payoutinformation'),
        ),
    ]
