# Generated by Django 5.2.11 on 2026-03-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_issuedticket_guest_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('advanced', 'Advanced'), ('premium', 'Premium')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('duration_days', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['duration_days'],
            },
        ),
    ]
