# Generated by Django 5.2.11 on 2026-04-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_order_vat_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
