# Generated by Django 5.2.11 on 2026-04-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_withdrawal_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredevent',
            name='amount_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Always NGN equivalent for reporting', max_digits=12),
        ),
        migrations.AddField(
            model_name='featuredevent',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
    ]
