# Generated by Django 5.2.11 on 2026-02-11 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('business_name', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=50)),
                ('tax_id', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=16)),
                ('companies_email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=20)),
                ('relevant_links', models.JSONField(blank=True, default=list)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('agree_to_terms', models.BooleanField(default=False)),
                ('role', models.CharField(default='host', max_length=20)),
                ('categories', models.ManyToManyField(blank=True, related_name='hosts', to='public.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HostLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('label', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
