# Generated by Django 5.2.11 on 2026-02-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='followers',
            field=models.IntegerField(default=0),
        ),
    ]
