# Generated by Django 5.2.11 on 2026-02-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_host_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='description',
            field=models.TextField(default='No Description', max_length=5000),
        ),
    ]
