# Generated by Django 5.2.11 on 2026-02-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_host_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
