# Generated by Django 5.2.11 on 2026-02-23 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_ticket_sold_count'),
        ('host', '0004_host_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commision', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.event')),
            ],
        ),
    ]
