# Generated by Django 5.2.11 on 2026-02-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0008_remove_affliateearnings_affliate_affiliatelink_and_more'),
        ('host', '0005_affliate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Affliate',
        ),
    ]
