# Generated by Django 5.2.11 on 2026-03-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0009_hostactivity_hostnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='companies_email',
        ),
        migrations.AlterField(
            model_name='host',
            name='business_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
