# Generated by Django 5.2.11 on 2026-03-22 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0010_remove_host_companies_email_alter_host_business_type_and_more'),
        ('payments', '0007_hostplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('free', 'Free')], default='free', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('plan_slug', models.CharField(default='free', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='host.host')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.hostplan')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
