# Generated by Django 5.2.11 on 2026-03-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0011_hostsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostsubscription',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
