# Generated by Django 5.2.11 on 2026-03-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0012_hostsubscription_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostsubscription',
            name='currency',
            field=models.CharField(default='NGN', help_text='Currency used for this subscription (NGN, USD, GHS, KES, ZAR, etc.)', max_length=3),
        ),
    ]
