# Generated by Django 5.2.11 on 2026-04-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0013_hostsubscription_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='show_my_events',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='host',
            name='show_past_events',
            field=models.BooleanField(default=True),
        ),
    ]
