# Generated by Django 5.2.11 on 2026-04-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0014_host_show_my_events_host_show_past_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostsubscription',
            name='auto_renew',
            field=models.BooleanField(default=False, help_text='Automatically renew this subscription 1 day before expiry.'),
        ),
    ]
