# Generated by Django 5.2.11 on 2026-04-04 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0015_hostsubscription_auto_renew'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('gifted_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifted_badges', to='host.host')),
            ],
        ),
    ]
