# Generated by Django 5.2.11 on 2026-04-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0016_verifiedbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='nin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='profile_banner',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
