# Generated by Django 5.2.11 on 2026-04-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0017_host_nin_host_profile_banner_host_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
