# Generated by Django 5.2.11 on 2026-04-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0018_host_verified'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='verifiedbadge',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('host',), name='unique_active_badge_per_host'),
        ),
    ]
