# Generated by Django 5.2.11 on 2026-04-13 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0019_verifiedbadge_unique_active_badge_per_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sends_used', models.PositiveIntegerField(default=0)),
                ('sms_sends_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_usage', to='host.host')),
                ('subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_usage', to='host.hostsubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
