# Generated by Django 5.2.11 on 2026-04-13 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0020_campaignusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_usage', to='host.host')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_usage', to='host.hostsubscription')),
            ],
        ),
    ]
