# Generated by Django 5.2.11 on 2026-04-14 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0021_featureusage'),
        ('transactions', '0014_featuredplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='issued_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='transactions.issuedticket'),
        ),
    ]
