# Generated by Django 5.2.11 on 2026-04-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0022_alter_checkin_issued_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='relevant_links',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
