# Generated by Django 5.2.11 on 2026-04-06 09:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_flaggeduser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_email', models.EmailField(max_length=254)),
                ('action', models.CharField(choices=[('user_suspend', 'User Suspended'), ('user_unsuspend', 'User Unsuspended'), ('user_flag', 'User Flagged'), ('user_unflag', 'User Unflagged'), ('host_suspend', 'Host Suspended'), ('host_unsuspend', 'Host Unsuspended'), ('host_approve', 'Host Verification Approved'), ('host_decline', 'Host Verification Declined'), ('event_suspend', 'Event Suspended'), ('event_unsuspend', 'Event Unsuspended'), ('event_delete', 'Event Deleted'), ('event_feature', 'Event Featured'), ('withdrawal_approve', 'Withdrawal Approved'), ('withdrawal_reject', 'Withdrawal Rejected'), ('other', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
