# Generated by Django 5.2.11 on 2026-04-06 15:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_adminauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('user_suspend', 'User Suspended'), ('user_unsuspend', 'User Unsuspended'), ('user_flag', 'User Flagged'), ('user_unflag', 'User Unflagged'), ('account_approval', 'Account Approval'), ('host_suspend', 'Host Suspended'), ('host_unsuspend', 'Host Unsuspended'), ('host_approve', 'Host Verification Approved'), ('host_decline', 'Host Verification Declined'), ('badge_gifting', 'Badge Gifted to Host'), ('auto_payout', 'Auto Payout Enabled/Disabled'), ('force_payout', 'Force Payout Initiated'), ('event_suspend', 'Event Suspended'), ('event_unsuspend', 'Event Unsuspended'), ('event_delete', 'Event Deleted'), ('event_feature', 'Event Featured'), ('event_pausing', 'Event Paused'), ('withdrawal_approve', 'Withdrawal Approved'), ('withdrawal_reject', 'Withdrawal Rejected'), ('account_suspension', 'Account Suspension'), ('ban', 'User / Host Banned'), ('other', 'Other')], max_length=30),
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('general', 'General'), ('policies', 'Policies'), ('fees', 'Fees & Commissions'), ('fraud', 'Fraud Detection'), ('notifications', 'Notifications'), ('localization', 'Localization')], max_length=30)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('default_value', models.JSONField()),
                ('label', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section', 'key'],
            },
        ),
    ]
