# Generated by Django 5.2.11 on 2026-04-21 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_alter_adminauditlog_action_systemconfig'),
        ('host', '0022_alter_checkin_issued_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('last_payout_date', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_payout', to='host.host')),
            ],
            options={
                'verbose_name': 'Auto Payout Configuration',
                'verbose_name_plural': 'Auto Payout Configurations',
                'db_table': 'transactions_auto_payout',
            },
        ),
    ]
