# Generated by Django 5.2.11 on 2026-04-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_autopayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='country_assignment',
            field=models.CharField(blank=True, help_text='Country this admin can view. Restricts all queries to this country.', max_length=30, null=True),
        ),
    ]
