"""
Django settings for Qavtix project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from celery.schedules import crontab
from decouple import config
import dj_database_url
import os
from datetime import timedelta

from authentication.utils import generate_apple_client_secret





# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")
DEBUG = config("DEBUG", default=False, cast=bool)
# settings.py

DATABASES = {
    'default': dj_database_url.parse(config('DATABASE_URL'))
}


ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #internal apps
    'administrator',
    'authentication',
    'host',
    'public',
    'attendee',  
    'notification',
    'events',
    'transactions',
    'payments',
    'marketplace',

     # Third-party apps
    "corsheaders",
    'rest_framework',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.apple',
    'rest_framework_simplejwt', 
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'anymail',
    "django_filters",
    "drf_spectacular",
    'django_celery_results',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware', 
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Qavtix.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Qavtix.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)



# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
  
    "EXCEPTION_HANDLER": "public.exceptions.custom_exception_handler",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS":  "public.pagination.CustomPagination",
    "PAGE_SIZE": 3,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Qavtix API",
    "DESCRIPTION": "Official API documentation for Qavtix",
    "ENUM_ADD_EXPLICIT_BLANK_NULL_CHOICE": False,
    "DISABLE_ERRORS_AND_WARNINGS": True,
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
     "COMPONENT_SPLIT_REQUEST": True,
     "ENUM_NAME_OVERRIDES": {
        "status": "EventStatusEnum"
    }
}



#Cors settings
# CORS_ALLOWED_ORIGINS = [
#     "http://127.0.0.1:5500",
#     "http://localhost:5500",
# ]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True


#Auth Library Settings 

REST_AUTH = {
    'TOKEN_MODEL': None,
    'USE_JWT': True,
}

SITE_ID = 1

REST_USE_JWT = True  # tells dj-rest-auth to use JWT instead of TokenModel
REST_USE_TOKENS = False  
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_EMAIL_VERIFICATION = "optional"  # or "mandatory" for production
SOCIALACCOUNT_AUTO_SIGNUP = True  # automatically create user if email not linked yet
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_ADAPTER = 'authentication.adapters.MySocialAccountAdapter'

CALLBACK_URL= config("CALLBACK_URL")
FACEBOOK_CALLBACK_URL = config("FACEBOOK_CALLBACK_URL")

APPLE_CLIENT_ID = os.getenv("APPLE_CLIENT_ID")
APPLE_TEAM_ID = os.getenv("APPLE_TEAM_ID")
APPLE_KEY_ID = os.getenv("APPLE_KEY_ID")
APPLE_PRIVATE_KEY = os.getenv("APPLE_PRIVATE_KEY")
APPLE_CLIENT_SECRET = os.getenv("APPLE_CLIENT_SECRET")
# APPLE_CLIENT_SECRET = generate_apple_client_secret()


SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": config("GOOGLE_CLIENT_ID"),
            "secret": config("GOOGLE_CLIENT_SECRET"),
            "key": ""
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    },
    "facebook": {
        "METHOD": "oauth2",
        "SCOPE": ["email", "public_profile"],
        "FIELDS": [
            "id",
            "email",
            "name",
            "first_name",
            "last_name",
        ],
        "APP": {
            "client_id": config("FACEBOOK_APP_ID"),
            "secret": config("FACEBOOK_APP_SECRET"),
            "key": ""
        }
    },
    "apple": {
        "APP": {
            "client_id": APPLE_CLIENT_ID,
            "secret": APPLE_CLIENT_SECRET,
            "key": APPLE_KEY_ID,
            "certificate_key": APPLE_PRIVATE_KEY,
        }
    }
}



SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=config("ACCESS_TOKEN_LIFETIME",cast=int)),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=config("REFRESH_TOKEN_LIFETIME",cast=int)),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}
PASSWORD_RESET_TOKEN_TTL_MINUTES = config("PASSWORD_RESET_TOKEN_TTL_MINUTES", cast=int)
PASSWORD_RESET_OTP_TTL_MINUTES = 3
PASSWORD_RESET_OTP_LENGTH = 6


USERNAME_FIELD = "email"
# AUTH_USER_MODEL = "users.User"
REST_AUTH_LOGIN_SERIALIZER = "authentication.serializers.EmailLoginSerializer"


EMAIL_BACKEND = "anymail.backends.brevo.EmailBackend"

ANYMAIL = {
    "BREVO_API_KEY": config("BREVO_API_KEY"),  
}


DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")



#PAYMENT SETTINGS
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY')
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY')
PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY')



#CELERY SETTINGS

CELERY_BROKER_URL = config("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_BACKEND = "django-db"
CELERY_RESULT_SERIALIZER = "json"


CELERY_BEAT_SCHEDULE = {
    'pending-order-reminder-every-5-min': {
        'task': 'payments.tasks.send_pending_order_reminders',
        'schedule': crontab(minute='*/5'),
    },
    'expire-pending-orders-every-15-min': {
        'task': 'payments.tasks.expire_pending_orders',
        'schedule': crontab(minute='*/15'),   # every 15 minutes
    },
    "expire-split-orders": {
        "task":     "payments.tasks.expire_split_orders",
        "schedule": crontab(minute="*/30"),  # every 30 minutes
    },
    "expire-featured-events": {
        "task":     "transactions.tasks.expire_featured_events",
        "schedule": crontab(minute="*/30"),  # every 30 minutes
    },
    "send-featured-expiry-reminders": {
        "task":     "transactions.tasks.send_featured_expiry_reminders",
        "schedule": crontab(minute=0),       # every hour
    },
    "expire-host-subscriptions": {
        "task":     "payments.tasks.expire_host_subscriptions",
        "schedule": crontab(minute="*/30"),
    },
    "send-host-plan-expiry-reminders": {
        "task":     "payments.tasks.send_plan_expiry_reminders",
        "schedule": crontab(minute=0),
    },
    "send-plan-expiry-reminders": {
        "task":     "payments.tasks.send_plan_expiry_reminders",
        "schedule": crontab(minute=0),
    },
     "auto-renew-host-subscriptions": {
        "task":     "payments.tasks.auto_renew_subscriptions",
        "schedule": crontab(hour=6, minute=0),   # daily at 06:00
    },
    'expire-attendee-subscriptions': {
        'task': 'payments.tasks.expire_attendee_subscriptions',
        'schedule': crontab(minute='*/30'),        # every 30 minutes
    },
    'send-attendee-plan-expiry-reminders': {
        'task': 'payments.tasks.send_attendee_plan_expiry_reminders',
        'schedule': crontab(minute=0),             # every hour
    },
    'auto-renew-subscriptions': {
        'task': 'host.tasks.auto_renew_subscriptions',
        'schedule': crontab(hour=0, minute=0),             # every hour
    },
    "flag-suspicious-users": {
    "task":     "administrator.tasks.flag_suspicious_users",
     "schedule": crontab(minute=0),  # every hour
    },
    'mark-past-events-as-ended': {
        'task': 'events.tasks.mark_past_events_as_ended',   # Change path if needed
        'schedule': crontab(minute='*/30'),                # Every 30 minutes
    },
    "activate-scheduled-events-every-minute": {
        "task": "events.tasks.activate_scheduled_events",  # adjust path
        "schedule": crontab(minute="*/1"),  # every minute
    },
    "auto_payout_friday_job": {
        "task": "administrator.tasks.run_friday_auto_payouts",
        "schedule": crontab(hour=9, minute=0, day_of_week=5),  # Friday 9AM
    }

}

FRONTEND_URL = config("FRONTEND_URL", default="https://qavtix.com")

CURRENCY_API_KEY = config("CURRENCY_API_KEY")



STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",   # ✅ REQUIRED
                "django.contrib.messages.context_processors.messages",  # ✅ REQUIRED
            ],
        },
    },
]