# Generated by Django 5.2.11 on 2026-02-18 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0001_initial'),
        ('host', '0002_host_followers'),
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_hosts', to='attendee.attendee')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='host.host')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attendee', 'host'), name='unique_attendee_host_follow')],
            },
        ),
    ]
