# Generated by Django 5.2.11 on 2026-02-19 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_host_description'),
        ('public', '0004_follow_created_at_alter_follow_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=200)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='host.host')),
            ],
        ),
    ]
