# Generated by Django 5.2.11 on 2026-03-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('city', 'email')},
            },
        ),
    ]
