# Generated by Django 5.2.11 on 2026-03-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_categorysubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
